FROM golang:1.25.1-alpine AS  builder
WORKDIR /app
COPY . . 
RUN go build -o trapped-mouse

FROM alpine:latest 
WORKDIR /app

COPY --from=builder app/trapped-mouse .

COPY maze.txt .

CMD [ "./trapped-mouse" ]